services:

  php_backend:
    build:
      context: ./backend
    container_name: php_backend
    ports:
      - "8000:80"
    environment:
      DB_HOST: ep-curly-silence-aq03d3xa-pooler.c-8.us-east-1.aws.neon.tech
      DB_NAME: neondb
      DB_USER: neondb_owner
      DB_PASSWORD: npg_X7T1aGYwNVEC
    volumes:
      - ./backend:/var/www/html