services:

  php_backend:
    build:
      context: ./backend
    container_name: php_backend
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: carrosdb
      DB_USER: root
      DB_PASSWORD: root
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrosdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d   # ✅ CORRETO

volumes:
  mysql_data: